Sync up the ve100 build to the ve050 base for auto builds on Linux.

diff --git a/trunk/source/org.eclipse.ve.releng.builder/tests/testScripts/runtests b/trunk/source/org.eclipse.ve.releng.builder/tests/testScripts/runtests
--- a/trunk/source/org.eclipse.ve.releng.builder/tests/testScripts/runtests
+++ b/trunk/source/org.eclipse.ve.releng.builder/tests/testScripts/runtests
@@ -3,8 +3,6 @@
 # by default, use the java executable on the path
 vm=java
 
-#set the DISPLAY for running tests on Linux
-DISPLAY=`$HOST`:0.0;export DISPLAY
 
 #this value must be set when using rsh to execute this script, otherwise the script will execute from the user's home directory
 dir=.
@@ -79,18 +77,18 @@ then
 		# if tests are to run without reinstalling eclipse, only install the test eclipse if it does not exist
 		# If the test-eclipse directory is in a partially installed state, it should be deleted manually
 
-		if [ ! -r test-eclipse/eclipse ]
+		if [ ! -r target/eclipse ]
 		then
 			 $vm -cp eclipse/startup.jar org.eclipse.core.launcher.Main -noupdate -ws $ws -os $os -arch $arch -application org.eclipse.ant.core.antRunner -file test.xml setup -Dws=$ws -Dos=$os -Darch=$arch -Dclean=true -logger org.apache.tools.ant.DefaultLogger
 		fi
 	fi
 
-# run tests
-$vm -cp eclipse/startup.jar org.eclipse.core.launcher.Main -noupdate -ws $ws -os $os -arch $arch -application org.eclipse.ant.core.antRunner -file test.xml $tests -Dws=$ws -Dos=$os -Darch=$arch -D$installmode=true $properties -logger org.apache.tools.ant.DefaultLogger
-
-# display message to user if os, ws and arch are invalid
-else
-	echo "The os, ws and arch values are either invalid or are an invalid combination"
-
-exit 1
+	# run tests
+	$vm -cp eclipse/startup.jar org.eclipse.core.launcher.Main -noupdate -ws $ws -os $os -arch $arch -application org.eclipse.ant.core.antRunner -file test.xml $tests -Dws=$ws -Dos=$os -Darch=$arch -D$installmode=true $properties -logger org.apache.tools.ant.DefaultLogger
+	
+	# display message to user if os, ws and arch are invalid
+	else
+		echo "The os, ws and arch values are either invalid or are an invalid combination"
+	
+	exit 1
 fi
